---
title: "codebook"
author: "B. Clark"
date: "27-04-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Codebook for Week 4 Getting and Cleaning assignment

This document describes the data used in the Week 4 assignment.

* subjectID - Sequential number for each of the 30 subjects from the training and test data sets

* activities -  
  * 1: WALKING  
  * 2: WALKING_UPSTAIRS  
  * 3: WALKING_DOWNSTAIRS  
  * 4: SITTING  
  * 5: STANDING  
  * 6: LAYING  

While there are 561 "measurable" variables in the training and test datasets, only 66 are Mean or Std variables.  These are selected and displayed in the output file "tidyData.txt".

The files (data) processed are the following:

* activity_labels.txt - Contains the IDs (1-6) and names of each of the six activities for which measurements were taken
* features.txt - Contains the names of each of the measurements (features taken for each activity.  These are used as the basis for the column names in the first merged dataset)
* y_train.txt - Contains the IDs (1-6) of each of the activities for which each measurement was taken in the training dataset
* subject_train.txt - Contains the IDs(1-30) of each of the subjects for the training dataset
* x_train.txt - The training dataset.  Contains measurements for each of the 561 features, for each activity and each subject.  However, the column names are not descriptive and the activity and subject IDs are not currently in this dataset, and must be merged from others.
* y_test.txt - Contains the IDs (1-6) of each of the activities for which each measurement was taken in the test dataset
* subject_test.txt - Contains the IDs(1-30) of each of the subjects for the test dataset
* x_test.txt - test training dataset.  Contains measurements for each of the 561 features, for each activity and each subject.  However, the column names are not descriptive and the activity and subject IDs are not currently in this dataset, and must be merged from others.

The run_analysis.R script works as described, making a number of data transformations and cleansing:

1) The activity IDs are bound on to the beginning of the training and test datasets
2) The subject IDs are bound on to the beginning of the training and test datasets
3) The training and test datasets are merged, to form a single dataset, merged_dt
4) The first two columns (subject and activity) are given descriptive names and the dataset is then ordered by these same variables
5) The script then loops through the features file, assigning each row of the dataset to each column of the measurements in the merged dataset, so as to make the column names much more descriptive. Reserved characters are stripped out and a unique number is given to each column, so as to not disable subsequent dplyr functions.
6) Only the measurement columns that are mean or standard deviation are stripped to be used in the final dataset.
7) The activity IDs are replaced with activity names (more descriptive).
8) The final dataset is grouped by subject and activity and a mean is calculated for each measureable variable against each subject/activity combination.
9) This tidy dataset is then written to the final output file, tidyData.txt
